### PR TITLE
fix: Add packageManager field to package.json

### PR DESCRIPTION
**Pull request by jacekradko**
Adding the `packageManager` field to package.json as well as the correct lock file. Updating deps

### CODE REVIEW

**Review by royanger — COMMENTED** [review]
Hey @jacekradko. The changes are solid, but the concern here is that we try to have the quickstart repos mimic the Quickstart guides as closely as possible. The Quickstart guides (and generally anything in docs) use `npm` as the primary recommendation for a package manager. To that end we'd want to keep `npm` in the README instructions. Would the package manager change cause any issues with `npm` or `yarn`?

**Comment by jacekradko** [comment]
@royanger If we want to use `npm` here, which makes sense, then I think it would make sense to get rid of the pnpm-specific `pnpm-lock.yaml` and check in `package-lock.json` which `npm` uses. Does that sound ok?

**Comment by royanger** [comment]
> @royanger If we want to use `npm` here, which makes sense, then I think it would make sense to get rid of the pnpm-specific `pnpm-lock.yaml` and check in `package-lock.json` which `npm` uses. Does that sound ok?

That is perfect.

**Comment by royanger** [comment]
Thanks @jacekradko! I was about to approve this but thanks for getting it done and merged!

**Pull request merged**
